name: UI Tests (Java 22) + Allure Pages

on:
  push:
    branches: [ master ]   # שנה ל-main אם צריך
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 22
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "22"
          cache: maven

      - name: Install Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run tests (headless)
        env:
          HEADLESS: "true"                                  # הקוד שלך יודע לקרוא מזה
          BROWSER_LANG: "he"
          CHROME_BIN: ${{ steps.chrome.outputs.chrome-path }} # Selenium ימצא את Chrome
        run: |
          java -version
          mvn -v
          mvn -U --batch-mode clean test \
            -Dmaven.compiler.release=22 \
            -Dmaven.compiler.fork=false \
            -Dfile.encoding=UTF-8 \
            -Dsurefire.printSummary=true

      # נבדוק אם יש תוצאות Allure לפני שנמשיך
      - name: Check Allure results
        id: check
        run: |
          if [ -d "target/allure-results" ] && [ "$(ls -A target/allure-results)" ]; then
            echo "has_results=true" >> $GITHUB_OUTPUT
          else
            echo "has_results=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate Allure HTML
        if: steps.check.outputs.has_results == 'true'
        run: |
          npx -y allure-commandline@latest generate target/allure-results \
            -o target/allure-report --clean

      - name: Configure GitHub Pages
        if: steps.check.outputs.has_results == 'true'
        uses: actions/configure-pages@v5

      - name: Upload report as Pages artifact
        if: steps.check.outputs.has_results == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/allure-report

      - name: Deploy to GitHub Pages
        if: steps.check.outputs.has_results == 'true'
        id: deploy
        uses: actions/deploy-pages@v4
