      - name: Build (diagnose compile) - no tests
        env:
          HEADLESS: "true"
          BROWSER_LANG: "he"
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
          CI: "true"
        run: |
          set -o pipefail
          # נריץ קומפילציה בלבד עם דיבאג מלא ובלי fork כדי להדפיס טעויות של javac
          mvn -e -X -Dmaven.compiler.fork=false -Dfile.encoding=UTF-8 -DskipTests compile | tee compile.log
          # נשמור עותק בטוח
          cp compile.log target/compile.log || true

      - name: Upload compile log (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compile-log
          path: target/compile.log
          if-no-files-found: ignore

      - name: Run tests (headless)
        # נריץ רק אם הקומפילציה הצליחה
        if: success()
        env:
          HEADLESS: "true"
          BROWSER_LANG: "he"
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
          CI: "true"
        run: |
          mvn --batch-mode test \
            -Dmaven.compiler.fork=false \
            -Dfile.encoding=UTF-8 \
            -Dsurefire.printSummary=true

      - name: Print Surefire reports on failure
        if: failure()
        run: |
          echo "=== Surefire reports (txt) ==="
          if ls target/surefire-reports/*.txt 1> /dev/null 2>&1; then
            for f in target/surefire-reports/*.txt; do
              echo "----- $f -----"
              cat "$f"
            done
          else
            echo "No *.txt reports found."
          fi

      - name: Generate Allure report (HTML)
        if: always()
        run: |
          if [ -d "target/allure-results" ]; then
            npx -y allure-commandline@latest generate target/allure-results -o target/allure-report --clean
          else
            echo "No target/allure-results found, skipping Allure HTML generation."
            mkdir -p target/allure-report
            echo "<html><body><h2>No Allure results were generated.</h2></body></html>" > target/allure-report/index.html
          fi

      - name: Setup Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/allure-report

      - name: Deploy to GitHub Pages
        id: deploy
        if: always()
        uses: actions/deploy-pages@v4
